### ISSUE TITLE
Can't upload in flutter web

### ISSUE THREAD

**Issue by DeecodeTeam** [apivideo/api.video-flutter-uploader#15]
### Version

1.2.1

### Environment that reproduces the issue

Browser: Chrome

### Use case description

I'm using file picker (https://pub.dev/packages/file_picker),  we can't access the file path in flutter web, all of your upload functions take the the file path as a string parameter

### Proposed solution

add additional parameters that will allow us to use the bytes of the file instead of the path

**Comment by ThibaultBee** [comment]
Hi,

This is something we should improve. But we got to find the type that is the more appropriate for web upload.

As a workaround, the example use https://pub.dev/packages/image_picker (official flutter package). image_picker returns the path. Could you consider using `image_picker` instead of `file_picker`?

**Comment by DeecodeTeam** [comment]
Ok thanks, I'll try

Le mar. 6 févr. 2024 à 05:21, Thibault Beyou ***@***.***> a
écrit :

**Comment by DeecodeTeam** [comment]
It works thanks
